deploy:
  provider: heroku
  api_key:
    secure: TLG4AJRoWD6MmZucQdOKmCyyDJcTIBsIsdPnrQ/DH6yblVpqF1Qy0+2Lir+cEQldoun2u9ShalED5JNqKeOeqSNRFcW41RDPrPVUut9r14B0C+JndYuk4UVD+18LCn6MjW9BQUmxI4H82NO9FjceDpv85VuGSCk+8+APV0+WYcA=
  app: philwilt
  on:
    repo: phillwilt/portfolio

bundler_args: --without development
